### ISSUE TITLE
User Friendly way to use it.

### ISSUE THREAD

**Issue by 03-134202-096** [ClementPla/FocusedAttention#3]
Is there any user friendly way to execute it?
Can you provide us Readme ?
THANKS

**Comment by ClementPla** [comment]
Hi,
Thanks for your interest and apologies for the slow response. I have been working on new "friendlier" repository. It includes a new implementation of the algorithm (functionally the same, but more efficient).
Please visit:
https://github.com/ClementPla/interpretability_toolkit
In particular the associated notebook. 
Please open an issue in the new repository if needed.
